<a href="https://colab.research.google.com/github/kevin-alvear/Tarea-10-Ejercicios-Descomposicion-LU/blob/main/%5BTarea_10%5D_ALVEAR_KEVIN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Escuela Politécnica Nacional

## Ejercicios de Descomposición LU


**Estudiante:** Kevin Alvear  
**Fecha:** 28/07/2024

---

**1. Realice las siguientes multiplicaciones matriz-matriz:**

a.
   \begin{bmatrix}
   2 & -3 \\
   3 & -1
   \end{bmatrix}
   \begin{bmatrix}
   1 & 5 \\
   2 & 0
   \end{bmatrix}

b.
   \begin{bmatrix}
   2 & -3 \\
   3 & -1
   \end{bmatrix}
   \begin{bmatrix}
   1 & 5 & -4 \\
   -3 & 2 & 0
   \end{bmatrix}

c.
   \begin{bmatrix}
   2 & -3 & 1 \\
   4 & 3 & 0 \\
   5 & 2 & -4
   \end{bmatrix}
   \begin{bmatrix}
   0 & 1 & -2 \\
   1 & 0 & -1 \\
   2 & 3 & -2
   \end{bmatrix}

d.
   \begin{bmatrix}
   2 & 1 & 2 \\
   -2 & 3 & 0 \\
   2 & -1 & 3
   \end{bmatrix}
   \begin{bmatrix}
   1 & -2 \\
   -4 & 1 \\
   0 & 2
   \end{bmatrix}

In [1]:
import numpy as np

# Matrices para el inciso a
A_a = np.array([[2, -3], [3, -1]])
B_a = np.array([[1, 5], [2, 0]])

# Matrices para el inciso b
A_b = np.array([[2, -3], [3, -1]])
B_b = np.array([[1, 5, -4], [-3, 2, 0]])

# Matrices para el inciso c
A_c = np.array([[2, -3, 1], [4, 3, 0], [5, 2, -4]])
B_c = np.array([[0, 1, -2], [1, 0, -1], [2, 3, -2]])

# Matrices para el inciso d
A_d = np.array([[2, 1, 2], [-2, 3, 0], [2, -1, 3]])
B_d = np.array([[1, -2], [-4, 1], [0, 2]])

# Multiplicaciones matriz-matriz
result_a = np.dot(A_a, B_a)
result_b = np.dot(A_b, B_b)
result_c = np.dot(A_c, B_c)
result_d = np.dot(A_d, B_d)

print("Resultado de a:")
print(result_a)
print("\nResultado de b:")
print(result_b)
print("\nResultado de c:")
print(result_c)
print("\nResultado de d:")
print(result_d)

Resultado de a:
[[-4 10]
 [ 1 15]]

Resultado de b:
[[ 11   4  -8]
 [  6  13 -12]]

Resultado de c:
[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]

Resultado de d:
[[ -2   1]
 [-14   7]
 [  6   1]]


**2. Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices:**

a.
   \begin{bmatrix}
   4 & 2 & 6 \\
   3 & 0 & 7 \\
   -2 & -1 & -3
   \end{bmatrix}

b.
   \begin{bmatrix}
   1 & 2 & 0 \\
   2 & 1 & -1 \\
   3 & 1 & 1
   \end{bmatrix}

c.
   \begin{bmatrix}
   1 & 1 & -1 & 1 \\
   0 & -2 & -4 & -2 \\
   2 & 1 & 1 & 5 \\
   -1 & 0 & -2 & -4
   \end{bmatrix}

d.
   \begin{bmatrix}
   4 & 0 & 0 & 0 \\
   6 & 7 & 0 & 0 \\
   9 & 11 & 1 & 0 \\
   5 & 4 & 1 & 1
   \end{bmatrix}

In [2]:
import numpy as np

# Matrices dadas
A_a = np.array([[4, 2, 6], [3, 0, 7], [-2, -1, -3]])
A_b = np.array([[1, 2, 0], [2, 1, -1], [3, 1, 1]])
A_c = np.array([[1, 1, -1, 1], [0, -2, -4, -2], [2, 1, 1, 5], [-1, 0, -2, -4]])
A_d = np.array([[4, 0, 0, 0], [6, 7, 0, 0], [9, 11, 1, 0], [5, 4, 1, 1]])

# Determinantes
det_a = np.linalg.det(A_a)
det_b = np.linalg.det(A_b)
det_c = np.linalg.det(A_c)
det_d = np.linalg.det(A_d)

# Verificación de no singularidad e inversas
inversas = {}

if det_a != 0:
    inversas['A_a'] = np.linalg.inv(A_a)
if det_b != 0:
    inversas['A_b'] = np.linalg.inv(A_b)
if det_c != 0:
    inversas['A_c'] = np.linalg.inv(A_c)
if det_d != 0:
    inversas['A_d'] = np.linalg.inv(A_d)

print("Determinantes:")
print(f"Det(A_a): {det_a}")
print(f"Det(A_b): {det_b}")
print(f"Det(A_c): {det_c}")
print(f"Det(A_d): {det_d}\n")

print("Inversas de matrices no singulares:")
for key, inv in inversas.items():
    print(f"Inversa de {key}:")
    print(inv)
    print()


Determinantes:
Det(A_a): 0.0
Det(A_b): -8.000000000000002
Det(A_c): 0.0
Det(A_d): 28.00000000000001

Inversas de matrices no singulares:
Inversa de A_b:
[[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]

Inversa de A_d:
[[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714 -0.         -0.        ]
 [ 0.10714286 -1.57142857  1.         -0.        ]
 [-0.5         1.         -1.          1.        ]]



**3. Resuelva los sistemas lineales 4 x 4 que tienen la misma matriz de coeficientes:**

a.
   \begin{aligned}
   x_1 - x_2 + 2x_3 - x_4 &= 6 \\
   x_1 - x_2 + 2x_3 - x_4 &= 1 \\
   2x_1 + x_2 + 3x_3 - 4x_4 &= -2 \\
   - x_2 + x_3 - x_4 &= 5
   \end{aligned}

b.
   \begin{aligned}
   x_1 - x_2 + 2x_3 - x_4 &= 6 \\
   x_1 - x_2 + 2x_3 - x_4 &= 1 \\
   2x_1 + x_2 + 3x_3 - 4x_4 &= 2 \\
   - x_2 + x_3 - x_4 &= -1
   \end{aligned}

In [3]:
import numpy as np

# Matriz de coeficientes (es la misma para ambos sistemas)
A = np.array([
    [1, -1, 2, -1],
    [1, -1, 2, -1],
    [2, 1, 3, -4],
    [0, -1, 1, -1]
])

# Vector de términos independientes para el sistema a
b_a = np.array([6, 1, -2, 5])

# Vector de términos independientes para el sistema b
b_b = np.array([6, 1, 2, -1])

# Resolución de los sistemas
try:
    x_a = np.linalg.solve(A, b_a)
    print("Solución del sistema a:")
    print(x_a)
except np.linalg.LinAlgError:
    print("El sistema a no tiene solución única.")

try:
    x_b = np.linalg.solve(A, b_b)
    print("\nSolución del sistema b:")
    print(x_b)
except np.linalg.LinAlgError:
    print("El sistema b no tiene solución única.")

El sistema a no tiene solución única.
El sistema b no tiene solución única.


**4. Encuentre los valores de ($\alpha$) que hacen que la siguiente matriz sea singular.**

A =
   \begin{bmatrix}
   1 & -1 & \alpha \\
   2 & 2 & 1 \\
   0 & \alpha & -\frac{1}{2}
   \end{bmatrix}

In [4]:
import sympy as sp

# Definir el símbolo alfa
alpha = sp.symbols('alpha')

# Definir la matriz A
A = sp.Matrix([
    [1, -1, alpha],
    [2, 2, 1],
    [0, alpha, -1/2]
])

# Calcular el determinante de A
det_A = A.det()
print(f"Determinante de A: {det_A}")

# Resolver la ecuación det(A) = 0 para alfa
alpha_solutions = sp.solve(det_A, alpha)
print(f"Valores de alfa que hacen que A sea singular: {alpha_solutions}")

Determinante de A: 2*alpha**2 - alpha - 2.0
Valores de alfa que hacen que A sea singular: [-0.780776406404415, 1.28077640640442]


**5. Resuelva los siguientes sistemas lineales:**

a.
   \begin{bmatrix}
   1 & 0 & 0 \\
   2 & 1 & 0 \\
   -1 & 0 & 1
   \end{bmatrix}
   \begin{bmatrix}
   2 & 3 & -1 \\
   0 & -2 & 1 \\
   0 & 0 & 3
   \end{bmatrix}
   \begin{bmatrix}
   x_1 \\
   x_2 \\
   x_3
   \end{bmatrix}
   =
   \begin{bmatrix}
   2 \\
   -1 \\
   1
   \end{bmatrix}

b.
   \begin{bmatrix}
   2 & 0 & 0 \\
   -1 & 1 & 0 \\
   3 & 2 & -1
   \end{bmatrix}
   \begin{bmatrix}
   1 & 1 & 1 \\
   0 & 1 & 2 \\
   0 & 0 & 1
   \end{bmatrix}
   \begin{bmatrix}
   x_1 \\
   x_2 \\
   x_3
   \end{bmatrix}
   =
   \begin{bmatrix}
   -1 \\
   3 \\
   0
   \end{bmatrix}

In [5]:
import numpy as np

# Sistema a
A1_a = np.array([
    [1, 0, 0],
    [2, 1, 0],
    [-1, 0, 1]
])

A2_a = np.array([
    [2, 3, -1],
    [0, -2, 1],
    [0, 0, 3]
])

b_a = np.array([2, -1, 1])

# Multiplicar las dos matrices del lado izquierdo
A_a = np.dot(A1_a, A2_a)

# Resolver el sistema resultante
x_a = np.linalg.solve(A_a, b_a)

print("Solución del sistema a:")
print(x_a)

# Sistema b
A1_b = np.array([
    [2, 0, 0],
    [-1, 1, 0],
    [3, 2, -1]
])

A2_b = np.array([
    [1, 1, 1],
    [0, 1, 2],
    [0, 0, 1]
])

b_b = np.array([-1, 3, 0])

# Multiplicar las dos matrices del lado izquierdo
A_b = np.dot(A1_b, A2_b)

# Resolver el sistema resultante
x_b = np.linalg.solve(A_b, b_b)

print("\nSolución del sistema b:")
print(x_b)

Solución del sistema a:
[-3.  3.  1.]

Solución del sistema b:
[ 0.5 -4.5  3.5]


**6. Factorice las siguientes matrices en la descomposición LU mediante el algoritmo de factorización LU con ($l_i = 1$) para todas las ($i$).**

a.
   \begin{bmatrix}
   2 & -1 & 1 \\
   3 & 3 & 9 \\
   3 & 3 & 5
   \end{bmatrix}

b.
   \begin{bmatrix}
   1.012 & -2.132 & 3.104 \\
   -2.132 & 4.096 & -7.013 \\
   3.104 & -7.013 & 0.014
   \end{bmatrix}

c.
   \begin{bmatrix}
   2 & 0 & 0 & 0 \\
   1 & 1.5 & 0 & 0 \\
   0 & -3 & 0.5 & 0 \\
   2 & -2 & 1 & 1
   \end{bmatrix}

d.
   \begin{bmatrix}
   2.1756 & 4.0231 & -2.1732 & 5.1967 \\
   -4.0231 & 6.0000 & 0 & 1.1973 \\
   -1.0000 & -5.2107 & 1.1111 & 0 \\
   6.0235 & 7.0000 & 0 & -4.1561
   \end{bmatrix}

In [6]:
import numpy as np
from scipy.linalg import lu

# Matriz a
A_a = np.array([
    [2, -1, 1],
    [3, 3, 9],
    [3, 3, 5]
])

# Matriz b
A_b = np.array([
    [1.012, -2.132, 3.104],
    [-2.132, 4.096, -7.013],
    [3.104, -7.013, 0.014]
])

# Matriz c
A_c = np.array([
    [2, 0, 0, 0],
    [1, 1.5, 0, 0],
    [0, -3, 0.5, 0],
    [2, -2, 1, 1]
])

# Matriz d
A_d = np.array([
    [2.1756, 4.0231, -2.1732, 5.1967],
    [-4.0231, 6.0000, 0, 1.1973],
    [-1.0000, -5.2107, 1.1111, 0],
    [6.0235, 7.0000, 0, -4.1561]
])

# Factorización LU
def factorize_LU(A):
    P, L, U = lu(A)
    return L, U

# Factorización de las matrices
L_a, U_a = factorize_LU(A_a)
L_b, U_b = factorize_LU(A_b)
L_c, U_c = factorize_LU(A_c)
L_d, U_d = factorize_LU(A_d)

print("Matriz A (a):")
print("L:")
print(L_a)
print("U:")
print(U_a)

print("\nMatriz A (b):")
print("L:")
print(L_b)
print("U:")
print(U_b)

print("\nMatriz A (c):")
print("L:")
print(L_c)
print("U:")
print(U_c)

print("\nMatriz A (d):")
print("L:")
print(L_d)
print("U:")
print(U_d)

Matriz A (a):
L:
[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]]
U:
[[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]

Matriz A (b):
L:
[[ 1.          0.          0.        ]
 [-0.68685567  1.          0.        ]
 [ 0.32603093 -0.21424728  1.        ]]
U:
[[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]

Matriz A (c):
L:
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 1.          0.66666667  1.          0.        ]
 [ 0.5        -0.5         0.375       1.        ]]
U:
[[ 2.          0.          0.          0.        ]
 [ 0.         -3.          0.5         0.        ]
 [ 0.          0.          0.66666667  1.        ]
 [ 0.          0.          0.         -0.375     ]]

Matriz A (d):
L:
[[ 1.          0.          0.          0.        ]
 [-0.66790072  1.          0.          0.        ]
 [ 0.361

**7. Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema lineal usando la descomposición LU y, a continuación, resuelva los siguientes sistemas lineales.**

a.
   \begin{aligned}
   2x_1 - x_2 + x_3 &= -1 \\
   3x_1 + 3x_2 + 9x_3 &= 0 \\
   3x_1 + 3x_2 + 5x_3 &= 4
   \end{aligned}
   
b.
   \begin{aligned}
   1.012x_1 - 2.132x_2 + 3.104x_3 &= 1.984 \\
   -2.132x_1 + 4.096x_2 - 7.013x_3 &= -5.049 \\
   3.104x_1 - 7.013x_2 + 0.014x_3 &= -3.895
   \end{aligned}  

c.
   \begin{aligned}
   2x_1 &= 3 \\
   x_1 + 1.5x_2 &= 4.5 \\
   -3x_2 + 0.5x_3 &= -6.6 \\
   2x_1 - 2x_2 + x_3 + x_4 &= 0.8
   \end{aligned}

d.
   \begin{aligned}
   2.1756x_1 + 4.0231x_2 - 2.1732x_3 + 5.1967x_4 &= 17.102 \\
   -4.0231x_1 + 6.0000x_2 + 1.1973x_4 &= -6.1593 \\
   -1.0000x_1 - 5.2107x_2 + 1.1111x_3 &= 3.0004 \\
   6.0235x_1 + 7.0000x_2 - 4.1561x_4 &= 0.0000
   \end{aligned}

In [7]:
import numpy as np
from scipy.linalg import lu

def lu_decomposition(A):
    P, L, U = lu(A)
    return P, L, U

def forward_substitution(L, b):
    y = np.zeros_like(b, dtype=np.double)
    for i in range(len(b)):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    return y

def backward_substitution(U, y):
    x = np.zeros_like(y, dtype=np.double)
    for i in range(len(y)-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    return x

def solve_lu(A, b):
    P, L, U = lu_decomposition(A)
    Pb = np.dot(P, b)
    y = forward_substitution(L, Pb)
    x = backward_substitution(U, y)
    return x

# Sistema a
A_a = np.array([
    [2, -1, 1],
    [3, 3, 9],
    [3, 3, 5]
])
b_a = np.array([-1, 0, 4])
x_a = solve_lu(A_a, b_a)
print("Solución del sistema a:")
print(x_a)

# Sistema b
A_b = np.array([
    [1.012, -2.132, 3.104],
    [-2.132, 4.096, -7.013],
    [3.104, -7.013, 0.014]
])
b_b = np.array([1.984, -5.049, -3.895])
x_b = solve_lu(A_b, b_b)
print("\nSolución del sistema b:")
print(x_b)

# Sistema c
A_c = np.array([
    [2, 0, 0, 0],
    [1, 1.5, 0, 0],
    [0, -3, 0.5, 0],
    [2, -2, 1, 1]
])
b_c = np.array([3, 4.5, -6.6, 0.8])
x_c = solve_lu(A_c, b_c)
print("\nSolución del sistema c:")
print(x_c)

# Sistema d
A_d = np.array([
    [2.1756, 4.0231, -2.1732, 5.1967],
    [-4.0231, 6.0000, 0, 1.1973],
    [-1.0000, -5.2107, 1.1111, 0],
    [6.0235, 7.0000, 0, -4.1561]
])
b_d = np.array([17.102, -6.1593, 3.0004, 0.0000])
x_d = solve_lu(A_d, b_d)
print("\nSolución del sistema d:")
print(x_d)

Solución del sistema a:
[ 1.  2. -1.]

Solución del sistema b:
[1. 1. 1.]

Solución del sistema c:
[  1.5  -5.4 -30.8  21.5]

Solución del sistema d:
[ 4.5834584   0.64756529 22.5539797   7.01162597]
